name: GitHub Runner
on: 
   - push

jobs:
    UbuntuEcho:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This is running on an Ubuntu runner"
                echo "Runner OS: $RUNNER_OS"
    EchoOnWindows:
          runs-on: windows-latest
          steps:
             - name: Show OS
               run: |
                echo "This is running on an Windows runner"
                echo "Runner OS: $RUNNER_OS"
                
              
