name: Expression_Workflow
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] print start-up data"
              if: ${{inputs.debug}} 
              run: |
                echo 'triggered by :${{github.event_name}}\n Branch: ${{github.ref}}\n Commit SHA: ${{github.sha}}\n Runner OS: ${{runner.os}}'
            - name: "[debug] Print when triggered from main"
              if: ${{inputs.debug && github.ref=='refs/heads/main'}}
              run: echo "I waas triggere from main"
            - name: "Greeting"
              run: echo "Thank you for running this ${{github.workflow}}  WorkFlow"