name: 09- Using Functions
on:
  pull_request:
  workflow_dispatch: 

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: Print PR title
        run: |
          echo "${{github.event.pull_request.title}}"
          cat << EOF
          ${{toJson(github.event.pull_request.labels)}}
          EOF
      - name: Bug steps
        if: ${{!cancelled() && contains(github.event.pull_request.title,'fix')}}
        run: echo "I am bug fix"
        
      - name: Failing step
        run: exit 4
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed"
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is canclled. "
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
        
